name: docs

on:
    push:
        branches:
            - main

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    gh-pages:
        runs-on: ubuntu-latest

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: yarn

            - name: Install dependencies
              run: yarn

            - name: Build libraries
              run: yarn build:libraries

            - name: Generate doc website
              run: yarn docs

            - name: Publish on Github Pages
              uses: crazy-max/ghaction-github-pages@v4
              with:
                  target_branch: gh-pages
                  build_dir: docs
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
